apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgresservice.name }}
spec:
  type: {{ .Values.postgresservice.service.type }}
  ports:
  - port: {{ .Values.postgresservice.service.port }}
    targetPort: {{ .Values.postgresservice.service.targetPort }}
  selector:
    app: {{ .Values.postgresservice.selector.app }}