apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace | default "default" }}
  name: {{ .Values.role.name }}
rules: 
{{ toYaml .Values.role.rules | indent 2 }}