apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.frontendHpa.name }}
  namespace: {{ .Values.frontendHpa.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.frontendHpa.scaleTargetRef.name }}
  minReplicas: {{ .Values.frontendHpa.minReplicas }}
  maxReplicas: {{ .Values.frontendHpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.frontendHpa.metrics.resource.target.averageUtilization }}