apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicyapi.name }}
  namespace: {{ .Release.Namespace | default "default" }}
spec:
  podSelector:
    matchLabels:
      {{- toYaml .Values.networkPolicyapi.matchLabels | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - {}