apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.networkPolicy.name }}
  namespace: {{ .Values.networkPolicy.namespace | default .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{ toYaml .Values.networkPolicy.podSelector | nindent 6 }}
  policyTypes: {{ toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  ingress: {{ toYaml .Values.networkPolicy.ingress | nindent 4 }}