apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
type: Opaque
data:
  postgres-db: {{ .Values.secret.postgresDbValue | b64enc }}
  postgres-user: {{ .Values.secret.postgresUserValue | b64enc }}
  postgres-password: {{ .Values.secret.postgresPasswordValue | b64enc }}
  service-account-key.json: {{ .Values.secret.serviceAccountKeyValue | b64enc}}