apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.api.service.name }}
spec:
  selector:
    app: {{ .Values.backend.api.app }}
  ports:
  - protocol: TCP
    port: {{ .Values.backend.api.service.port }}
    targetPort: {{ .Values.backend.api.service.targetPort }}
  type: {{ .Values.backend.api.service.type }}